=== Deploy with Control Tower

You can deploy this Quick Start in a customized AWS Control Tower environment to help you set up a secure, multi-account AWS environment using AWS best practices. For details, see Customizations for AWS Control Tower.

The root directory of the Quick Start repository includes a _ct_ folder with a _manifest.yaml_ file to assist you with the AWS Control Tower deployment. This file has been customized for the Quick Start.

In the following sections, you will review and update the settings in this file and then upload it to the S3 bucket that is used for the deployment.

. Review the _manifest.yaml_ file. Navigate to the root directory of the Quick Start and open the _manifest.yaml_ file, located in the _ct_ folder.
. Confirm that the *region* attribute references the Region where AWS Control Tower is deployed. The default Region is us-east-1. You will update the regions attribute (located in the resources section) in a later step.
. Confirm that the *resource_file* attribute points to the public S3 bucket for the Quick Start. Using a public S3 bucket ensures a consistent code base across the different deployment options. If you prefer to deploy from your own S3 bucket, update the path as needed.
. Review each of the *parameters* attributes and update them as needed to match the requirements of your deployment.
. Confirm that the *deployment_targets* attribute is configured for either your target accounts or organizational units (OUs).
. For the *regions* attribute, add the Region where you plan to deploy the Quick Start. The default Region is us-east-1.
. Upload the _manifest.yaml_ file. Compress the manifest.yaml file and name it custom-control-tower-configuration.zip.
. Upload the _custom-control-tower-configuration.zip_ file to the S3 bucket that was created for the AWS Control Tower deployment (custom-control-tower-configuration-<accountnumber>-<region>). The file upload initiates the customized pipeline that deploys the Quick Start to your target accounts.