To deploy {partner-product-short-name} on AWS, complete the following steps. The stack takes about {deployment_time} to launch.

. Confirm that you have the https://docs.aws.amazon.com/cdk/v2/guide/getting_started.html#getting_started_prerequisites[prerequisites^] to install the AWS CDK.
. Install the AWS CDK.
. Clone the {partner-product-short-name} Quick Start repository:
```
git clone https://github.com/aws-quickstart/quickstart-{partner-product-name}.git
cd quickstart-{partner-product-name}
```
[start=4]
. Build the project:
```
npm install
npm run build
```
[start=5]
. Bootstrap your AWS environment:
```
cdk bootstrap
```
[start=6]
. Deploy to a new VPC:
```
npm run build && cdk deploy
```
[start=7]
. Alternatively, deploy the stack to an existing VPC:
```
npm run build && cdk deploy -c ExistingVPC=true --parameters VpcId=vpc-0c7910af2c48bffff --parameters PrivSubnets=subnet-08a3625e03ebbffff,subnet-0cb32f56d8757ffff
```

=== Command-line notes
* `-c ExistingVPC=true` means you're using an existing VPC instead of creating a new one.
* `--parameters VpcId=vpc-0c7910af2c48bffff` means the stack is created in the assigned VPC.
* `--parameters PrivSubnets=subnet-08a3625e03ebbffff,subnet-0cb32f56d8757ffff` means that the two private subnets are used in hosting compute resources (for example, for AWS Lambda and SageMaker Endpoint).