// Add a watermark for non-production builds
ifndef::production_build[]
[.watermark]
[discrete]
== DRAFT
endif::production_build[]
[.text-center]
[discrete]
== {partner-product-name} on AWS
:doctitle: {partner-product-name} on AWS for CFN
:!toc:
[.text-left]
include::../../{includedir}/introduction.adoc[]

== Overview
ifndef::production_build[]
_**This portion of the deployment guide is located in `docs/{guideroot}/{specificdir}/overview.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../../{guideroot}/{specificdir}/overview.adoc[]
ifndef::production_build[]
|===
endif::production_build[]


== Costs and licenses
ifndef::production_build[]
_**This portion of the deployment guide is located in `docs/{guideroot}/{specificdir}/licenses.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../../{guideroot}/{specificdir}/licenses.adoc[]
ifndef::production_build[]
|===
endif::production_build[]

== Architecture
ifndef::production_build[]
_**This portion of the deployment guide is located in `docs/{guideroot}/{specificdir}/architecture.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../../{guideroot}/{specificdir}/architecture.adoc[]
ifndef::production_build[]
|===
endif::production_build[]

== Deployment options
ifndef::production_build[]
_**This portion of the deployment guide is located in `docs/{guideroot}/{specificdir}/deployment_options.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../../{guideroot}/{specificdir}/deployment_options.adoc[]
ifndef::production_build[]
|===
endif::production_build[]

ifndef::production_build[]
_**This portion of the deployment guide is located in `docs/{guideroot}/{specificdir}/pre_deployment.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../../{guideroot}/{specificdir}/pre_deployment.adoc[]
ifndef::production_build[]
|===
endif::production_build[]


== Deployment steps
include::../../{includedir}/deployment_steps_cfn.adoc[]

ifndef::production_build[]
_**This portion of the deployment guide is located in `docs/{guideroot}/{specificdir}/post_deployment.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../../{guideroot}/{specificdir}/post_deployment.adoc[]
ifndef::production_build[]
|===
endif::production_build[]


== Troubleshooting
ifndef::production_build[]
_**This portion of the deployment guide is located in `docs/{guideroot}/{specificdir}/troubleshooting.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../../{guideroot}/{specificdir}/troubleshooting.adoc[]
ifndef::production_build[]
|===
endif::production_build[]
